services:
  - type: web
    name: qds-threat-detection
    env: docker
    region: ohio
    plan: free
    branch: ojasv
    envVars:
      - key: PORT
        value: "8000"
    secretFiles:
      - name: firebase-credentials.json
        content: '{ "paste_your_service_account_json": "here" }'
